baseURL = 'https://g-song-i.github.io'
languageCode = 'en-us'
title = 'Zongi Diary'
theme = "hugo-digital-garden-theme"
themesdir = "./themes/"
# robots.txt
# enableRobotsTXT = true

[module]
  [module.hugoVersion]
    min = "0.81.0"
    max = "0.84.2"

[params]
  name = "Songi's IT Dairy"
  description = "Hello 🤗 Welcome to my technical dairy. I'm gonna share my experiences and technical journey through the blog"
  initials = "SI"
  googleAnalytics = ""

  [[params.social]]
    name = "Github"
    link = "https://github.com/g-song-i"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/songi-gwak-934666227"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Posts"
    url = "/recent_projects/"
    weight = 1
  [[menu.main]]
    name = "Korean Posts"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Another"
    url = "/garden/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'
  recent_projects_tags = 'recent_projects_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'